import xml.etree.ElementTree as ET
from xml.dom import minidom

def escape_text(text):
    if not text:
        return ""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")

class SVGRenderer:
    def __init__(self, width, height, theme="light"):
        from .theme import PALETTES, FONTS
        self.width = width
        self.height = height
        self.theme = theme
        self.palette = PALETTES[theme]
        self.fonts = FONTS
        self.elements = []
        
        # Add root and definitions
        self.svg = ET.Element('svg', {
            'xmlns': 'http://www.w3.org/2000/svg',
            'viewBox': f"0 0 {width} {height}",
            'width': "100%",
            'height': "100%"
        })
        
        # Add background
        ET.SubElement(self.svg, 'rect', {
            'width': '100%',
            'height': '100%',
            'fill': self.palette['bg']
        })

    def add_rect(self, x, y, w, h, fill="none", stroke="none", rx=0, stroke_width=1):
        rect = ET.SubElement(self.svg, 'rect', {
            'x': str(x),
            'y': str(y),
            'width': str(w),
            'height': str(h),
            'fill': fill,
            'stroke': stroke,
            'rx': str(rx)
        })
        if stroke != "none":
            rect.set('stroke-width', str(stroke_width))
            
    def add_text(self, text, x, y, font_family, font_size, fill, font_weight="normal", letter_spacing="normal"):
        txt = ET.SubElement(self.svg, 'text', {
            'x': str(x),
            'y': str(y),
            'font-family': font_family,
            'font-size': str(font_size),
            'fill': fill,
            'font-weight': str(font_weight),
            'letter-spacing': str(letter_spacing)
        })
        txt.text = escape_text(text)

    def add_line(self, x1, y1, x2, y2, stroke, stroke_width=1):
        ET.SubElement(self.svg, 'line', {
            'x1': str(x1),
            'y1': str(y1),
            'x2': str(x2),
            'y2': str(y2),
            'stroke': stroke,
            'stroke-width': str(stroke_width)
        })

    def render(self):
        # Format the XML
        rough_string = ET.tostring(self.svg, 'utf-8')
        reparsed = minidom.parseString(rough_string)
        # Remove extra whitespace generated by minidom to keep it tight, or just return basic string
        return reparsed.toprettyxml(indent="  ")
